# GitLab CI for gentooinstall

image: python:3.12

before_script:
  - python -m pip install --upgrade pip
  - pip install .[dev]

stages:
  - lint
  - test
  - build

mypy:
  stage: lint
  script:
    - mypy --config-file pyproject.toml

flake8:
  stage: lint
  script:
    - flake8

pytest:
  stage: test
  script:
    - pytest

build_wheel:
  stage: build
  script:
    - pip install build
    - python -m build --wheel --no-isolation
  artifacts:
    paths:
      - dist/*.whl
    expire_in: 1 week
