on:
  pull_request:
    paths:
      - 'gentooinstall/locales/**'

name: Verify locale generation

jobs:
  translation-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Verify all translation scripts are up to date
        run: |
          cp -r gentooinstall /tmp/gentooinstall_orig
          (cd gentooinstall/locales && bash locales_generator.sh)
          diff -ru /tmp/gentooinstall_orig/locales gentooinstall/locales || (echo "Translation files are out of date. Re-run locales_generator.sh and commit the results." && exit 1)
